name: Build Docker image

on:
  push:
    branches: main

jobs:
  main:
    runs-on: [self-hosted]
    steps:
      -
        name: Login to DockerHub
        run: |
          docker login -u ${{ secrets.dockerhub_username }} -p ${{ secrets.dockerhub_password }}
      -
        name: Build and push
        run: |
          docker build -t dhutsj/es_helper:latest .
          docker push dhutsj/es_helper:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
