name: k8s deploy app

on:
  push:
    branches: main

jobs:
  main:
    runs-on: [self-hosted, k8s]
    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 15      
      - 
        name: Deploy
        run: |
          echo "k8s deploy app"
          pwd
          ls -l
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml 
